server:
  port: 10000

spring:
  application:
    name: jobportal-backend
  datasource:
    url: jdbc:h2:mem:jobportal_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    expiration-ms: 86400000 # 24 hours
  cors:
    allowed-origins: "http://localhost:4200,http://127.0.0.1:4200"
  webrtc:
    stun-servers: "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302"
    turn-servers: ""

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jobportal}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
